version: '2'
services:
  slave:
    build: ./builder
    image: jc888/base
    expose:
     - "22"
    ports:
     - "2212:22"
    links:
     - "webapp_1"
     - "webapp_2"
     - "loadbalancer"
    working_dir: /root/shared/ansible
    volumes:
     - .:/root/shared
     - /var/run/docker.sock:/var/run/docker.sock

  jenkins:
    image: jenkins
    links:
     - "slave"
    ports:
     - "8082:8080"
     - "50000:50000"
    volumes:
     - ./jenkins:/var/jenkins_home

  webapp_1:
    image: jc888/base
    expose:
     - "22"
    ports:
     - "8083:80"
     - "2213:22"

  webapp_2:
    image: jc888/base
    expose:
     - "22"
    ports:
     - "8084:80"
     - "2214:22"

  loadbalancer:
    image: jc888/base
    links:
     - "webapp_1"
     - "webapp_2"
    expose:
     - "22"
    ports:
     - "8081:80"
     - "2211:22"